##############################################################################
# Copyright (c) 2017 ZTE Corporation and others.
#
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Apache License, Version 2.0
# which accompanies this distribution, and is available at
# http://www.apache.org/licenses/LICENSE-2.0
##############################################################################

- name: install development tools for Debian family
  package:
    name: build-essential
    state: present
  when: ansible_os_family == "Debian"

- name: install development tools for RedHat family
  yum:
    name: '{{ item }}'
    state: present
  when: ansible_os_family == "RedHat"
  with_items:
    - "@Development tools"
    - gcc-c++
