##############################################################################
# Copyright (c) 2017 ZTE Corporation and others.
# zhihui.wu1@zte.com.cn
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Apache License, Version 2.0
# which accompanies this distribution, and is available at
# http://www.apache.org/licenses/LICENSE-2.0
##############################################################################

- hosts: hosts
  become: yes
  remote_user: root

  tasks:
    - set_fact:
        is_dhrystone: "{{ dhrystone | default(False) }}"
        is_whetstone: "{{ whetstone | default(False) }}"
        timestamp: "{{ lookup('pipe', 'date +%Y-%m-%d-%H-%M') }}"

    - name: Make some directories needed
      file:
        path: '{{ ansible_env.HOME }}/qtip_result/{{ timestamp }}/{{ ansible_hostname }}'
        state: directory

    - include: ../inxi.yaml
      vars:
        dest_path: '{{ ansible_env.HOME }}/qtip_result/'

    - include: ../top.yaml
      vars:
        dest_path: '{{ ansible_env.HOME }}/qtip_result/'

    - include: ./dhrystone.yaml
      when: "{{ is_dhrystone }}"

    - include: ./whetstone.yaml
      when: "{{ is_whetstone }}"